# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q385v5O89DPVwT5sWUG0qxAdyLrAZl6d
"""

import streamlit as st
import pandas as pd
import pickle
import plotly.express as px

# -------------------------------
# Load model and scaler
# -------------------------------
model = pickle.load(open('kmeans2.pkl', 'rb'))
scaler = pickle.load(open('scaler2.pkl', 'rb'))

# -------------------------------
# Cluster labels
# -------------------------------
cluster_names = {
    0: "Developing 🌱",
    1: "Emerging ⚡",
    2: "Developed 🌍"
}

# -------------------------------
# Title
# -------------------------------
st.title("🌍 Country Development Clustering App")

# -------------------------------
# Sidebar Inputs
# -------------------------------
st.sidebar.header("Enter Country Details")

gdp = st.sidebar.number_input("GDP", value=1000000000000.0)
birth_rate = st.sidebar.number_input("Birth Rate", value=20.0)
co2 = st.sidebar.number_input("CO2 Emissions", value=1000000.0)

# -------------------------------
# Create user input dataframe
# -------------------------------
features = ['GDP', 'Birth Rate', 'CO2 Emissions']

user_input = pd.DataFrame([[gdp, birth_rate, co2]], columns=features)

# -------------------------------
# Scale + Predict
# -------------------------------
user_scaled = scaler.transform(user_input)
cluster = model.predict(user_scaled)[0]
cluster_label = cluster_names[cluster]

# -------------------------------
# Show prediction
# -------------------------------
st.success(f"🌍 This country belongs to: {cluster_label} (Cluster {cluster})")

# -------------------------------
# Load dataset
# -------------------------------
df = pd.read_csv("your_dataset.csv")  # 👈 change filename

X = df[features]
X_scaled = scaler.transform(X)

df['Cluster'] = model.predict(X_scaled)
df['Cluster_Name'] = df['Cluster'].map(cluster_names)

# -------------------------------
# Visualization
# -------------------------------
fig = px.scatter(
    df,
    x='GDP',
    y='CO2 Emissions',
    color='Cluster_Name',
    title="Cluster Distribution (Your Input Included)",
    hover_data=['Birth Rate', 'Cluster_Name']
)

# -------------------------------
# Add USER POINT ⭐
# -------------------------------
fig.add_scatter(
    x=[gdp],
    y=[co2],
    mode='markers',
    marker=dict(size=14, color='black', symbol='star'),
    name='Your Input ⭐'
)

# -------------------------------
# Show plot
# -------------------------------
st.plotly_chart(fig)