# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q385v5O89DPVwT5sWUG0qxAdyLrAZl6d
"""

import streamlit as st
import pandas as pd
import pickle

st.title("🌍 Country Clustering App")

# Upload file
uploaded_file = st.file_uploader("Upload your dataset (CSV)", type=["csv"])

if uploaded_file is not None:

    df = pd.read_csv(uploaded_file)

    st.write("### Raw Data")
    st.write(df.head())

    # -----------------------------
    # DATA CLEANING
    # -----------------------------
    try:
        df['GDP'] = df['GDP'].replace(r'[\$,]', '', regex=True).astype(float)
        df['CO2 Emissions'] = df['CO2 Emissions'].replace(',', '', regex=True).astype(float)
        df['Birth Rate'] = pd.to_numeric(df['Birth Rate'], errors='coerce')
    except:
        st.error("Column names not matching! Please check your dataset.")
        st.stop()

    # Select features
    features = ['GDP', 'Birth Rate', 'CO2 Emissions']
    X = df[features]

    # Handle missing values
    X.fillna(X.mean(), inplace=True)

    # -----------------------------
    # LOAD MODEL + SCALER
    # -----------------------------
    try:
        scaler = pickle.load(open('scaler.pkl', 'rb'))
        kmeans = pickle.load(open('kmeans.pkl', 'rb'))
    except:
        st.error("Model files not found! Upload scaler.pkl and kmeans.pkl")
        st.stop()

    # Scale data
    X_scaled = scaler.transform(X)

    # Predict clusters
    clusters = kmeans.predict(X_scaled)

    # Add cluster column
    df['Cluster'] = clusters

    st.write("### Clustered Data")
    st.write(df.head())

    # -----------------------------
    # VISUALIZATION
    # -----------------------------
    st.write("### Cluster Visualization")

    import plotly.express as px

    fig = px.scatter(
        df,
        x='GDP',
        y='CO2 Emissions',
        color=df['Cluster'].astype(str),
        hover_name=df.columns[0]  # first column (country name)
    )

    st.plotly_chart(fig)

    # Download option
    csv = df.to_csv(index=False).encode('utf-8')
    st.download_button(
        "Download Clustered Data",
        csv,
        "clustered_data.csv",
        "text/csv"
    )