# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q385v5O89DPVwT5sWUG0qxAdyLrAZl6d
"""

import streamlit as st
import numpy as np
import pickle
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Country Clustering App", layout="centered")

st.title("🌍 Country Development Predictor")

st.write("Enter country details to predict whether it is Developed or Developing")

# -----------------------------
# USER INPUT
# -----------------------------
gdp = st.number_input("GDP (Example: 3000000000000)", min_value=0.0)
birth_rate = st.number_input("Birth Rate (Example: 15.2)", min_value=0.0)
co2 = st.number_input("CO2 Emissions (Example: 2500000)", min_value=0.0)

# -----------------------------
# LOAD MODEL
# -----------------------------
scaler = pickle.load(open('scaler2.pkl', 'rb'))
kmeans = pickle.load(open('kmeans2.pkl', 'rb'))

# -----------------------------
# PREDICTION
# -----------------------------
if st.button("Predict"):

    # Input array
    input_data = np.array([[gdp, birth_rate, co2]])

    # Scale
    input_scaled = scaler.transform(input_data)

    # Predict cluster
    cluster = kmeans.predict(input_scaled)[0]

    # -----------------------------
    # CLUSTER INTERPRETATION
    # -----------------------------
    if cluster == 0:
        result = "Developed Country 🌟"
    elif cluster == 1:
        result = "Developing Country 🌱"
    else:
        result = "Underdeveloped Country ⚠️"

    st.success(f"Predicted Cluster: {cluster}")
    st.subheader(result)

    # -----------------------------
    # VISUALIZATION
    # -----------------------------
    st.write("### 📊 Cluster Visualization")

    # Sample dataset (for plotting reference clusters)
    data = pd.DataFrame({
        'GDP': [1e12, 5e12, 2e12, 8e11, 3e12],
        'CO2': [1e6, 5e6, 2e6, 8e5, 3e6],
        'Cluster': [0, 1, 2, 0, 1]
    })

    # Add user input point
    user_df = pd.DataFrame({
        'GDP': [gdp],
        'CO2': [co2],
        'Cluster': [cluster]
    })

    # Combine
    plot_df = pd.concat([data, user_df], ignore_index=True)

    fig = px.scatter(
        plot_df,
        x='GDP',
        y='CO2',
        color=plot_df['Cluster'].astype(str),
        title="Cluster Distribution (Your Input Included)"
    )

    st.plotly_chart(fig)